### ISSUE TITLE
jak włączyć?

### ISSUE THREAD

**Issue by Boberkraft** [kaminskil1337/PoznajKaszuby#1]
![Zrzut ekranu 2022-01-14 o 09 29 04](https://user-images.githubusercontent.com/16669574/149476118-1208338e-28c7-4991-9251-6d3556c1e1b6.png)

**Comment by kaminskil1337** [comment]
poprawiłem, spróbuj teraz

**Comment by kaminskil1337** [comment]
poprawiłem, spróbuj teraz

**Comment by Boberkraft** [comment]
```
➜  PoznajKaszuby git:(master) java Main.java
Error: Could not find or load main class Main.java
Caused by: java.lang.ClassNotFoundException: Main.java
➜  PoznajKaszuby git:(master) 
```

**Comment by kaminskil1337** [comment]
spróbuj wpisać najpierw: javac Main.java,
a potem java Main

**Comment by Boberkraft** [comment]
musiałem usunąc pliki `.class` chyba

**Comment by Boberkraft** [comment]
Zajebiste puzzle  :D

**Comment by kaminskil1337** [comment]
Dzięki :))
